services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JambageCom\Div2007\:
    resource: '../Classes/'
    exclude: ['../Classes/{Api,Captcha,Compatibility,Constants,Database,Middleware,Security,SessionHandler,Utility}/']

  JambageCom\Div2007\Base\TranslationBase:
    public: true
    shared: false



